// preguntas.js
// Bancos de preguntas de los exámenes de ascenso (fuente: Manual de Operaciones).
// Lo usan el examen (index.html) y el Campus de Ascensos (panel de Capacitación),
// que lo carga desde https://examenes-emi.vercel.app/preguntas.js.

/* ===========================================================
   PREGUNTAS (fuente: Manual de Operaciones Sabores Express)
   correcta = índice de la opción correcta (0 = primera).
   Al comenzar, el orden de preguntas y de opciones se mezcla al azar.
   Grilla: correcta = [colFila1, colFila2, ...] (no se mezcla).
   =========================================================== */

// Nivel 1 — Entrenador: productos, equipos, higiene y atención.
const PREGUNTAS_ENTRENADOR = [
  { id:1, texto:"¿Cuál es el tiempo de cinta del horno BURNER?",
    opciones:["5 a 7 minutos","6 a 8 minutos","3 a 5 minutos","10 a 11 minutos"], correcta:0 },
  { id:2, texto:"¿A qué temperatura se cocinan las empanadas en el horno de cinta?",
    opciones:["265 °C a 280 °C","200 °C a 220 °C","230 °C a 250 °C","150 °C a 180 °C"], correcta:0 },
  { id:3, texto:"¿Cuál es la cantidad máxima de empanadas por bandeja para hornear?",
    opciones:["8 unidades, sin que se toquen","6 unidades","10 unidades","12 unidades"], correcta:0 },
  { id:4, texto:"¿Cuál es el vencimiento de las empanadas de jamón y queso y de jamón y roquefort?",
    opciones:["7 días","5 días","3 días","9 días"], correcta:0 },
  { id:5, texto:"¿Cuál es el vencimiento del resto de los gustos de empanadas?",
    opciones:["5 días","7 días","3 días","10 días"], correcta:0 },
  { id:6, texto:"¿Qué temperatura interna debe registrar el pirómetro en una empanada cocida?",
    opciones:["Entre 55 °C y 65 °C","Entre 40 °C y 50 °C","Entre 70 °C y 90 °C","Entre 30 °C y 45 °C"], correcta:0 },
  { id:7, texto:"Medialunas: tiempo de leudado y armado de bandeja.",
    opciones:["8 horas exactas, 28 por bandeja en 4 filas de 7","7 horas, 28 por bandeja en 4 filas de 7","8 horas, 32 por bandeja en 4 filas de 8","6 horas, 24 por bandeja en 4 filas de 6"], correcta:0 },
  { id:8, texto:"¿Cuántas chipás se colocan por bandeja para descongelar?",
    opciones:["60 unidades (6 filas de 10)","50 unidades (5 filas de 10)","40 unidades (4 filas de 10)","72 unidades (6 filas de 12)"], correcta:0 },
  { id:9, texto:"¿Cuántos criollitos se colocan en la placa para su cocción?",
    opciones:["21 unidades (3 filas de 7)","20 unidades (4 filas de 5)","28 unidades (4 filas de 7)","24 unidades (3 filas de 8)"], correcta:0 },
  { id:10, texto:"¿Cuántas pizzas se colocan por estante en la heladera?",
    opciones:["5 por estante, sectorizadas por gusto","4 por estante","6 por estante","3 por estante"], correcta:0 },
  { id:11, texto:"¿A qué temperatura debe estar la cámara de frío?",
    opciones:["0 °C a 5 °C","-15 °C a -20 °C","5 °C a 10 °C","-5 °C a 0 °C"], correcta:0 },
  { id:12, texto:'¿Qué significa el método "PEPS"?',
    opciones:["Primero en entrar, primero en salir","Primero en vencer, primero en salir","Primero en encargar, primero en sacar","Productos en perfecto estado"], correcta:0 },
  { id:13, texto:"Cuando llega mercadería de fábrica, ¿cómo se ordena en la heladera?",
    opciones:["Lo nuevo abajo y lo que ya estaba en stock arriba","Lo nuevo arriba y lo viejo abajo","Todo mezclado por gusto","Lo nuevo al fondo de la cámara sin rotular"], correcta:0 },
  { id:14, tipo:"grilla", texto:"Completá con el color de trapo correspondiente.",
    filas:["Limpieza de baños","Superficies y utensilios en contacto con alimentos","Limpieza de equipos (hornos, heladeras)"],
    columnas:["Verde","Azul","Amarillo"], correcta:[2,0,1] },
  { id:15, texto:"¿Cómo se prepara el agua sanitizada y cuánto dura?",
    opciones:["2 tapas de lavandina en 2 litros de agua, vence a las 4 horas","1 tapa de lavandina en 5 litros, vence a las 8 horas","2 tapas en 1 litro, vence a las 24 horas","Media tapa en 2 litros, dura todo el turno"], correcta:0 },
  { id:16, texto:"Además de al ingresar, después del baño o de tocar dinero, ¿cada cuánto nos lavamos las manos?",
    opciones:["Cada 1 hora","Cada 4 horas","Solo al terminar el turno","Una vez por turno"], correcta:0 },
  { id:17, texto:"¿Cuándo se pintan las medialunas con almíbar?",
    opciones:["Únicamente al momento de la entrega al cliente, con pincel de silicona","Apenas salen del horno, con pincel de cerdas","Antes de hornearlas","Al abrir el local, todas juntas"], correcta:0 },
  { id:18, texto:"Un cliente va a llevar 2 empanadas. ¿Qué le ofrecemos?",
    opciones:["La promo de 3 empanadas + gaseosa","Nada, ya decidió","Media docena","Un descuento en la próxima compra"], correcta:0 },
  { id:19, texto:"¿Cuál de los siguientes extintores es el más versátil por cubrir casi todos los tipos de fuego?",
    opciones:["Extintor ABC","Extintor K","Extintor de agua","Extintor de espuma"], correcta:0 },
  { id:20, texto:"¿Qué va en el tacho verde (reciclables)?",
    opciones:["Tickets, cartón seco, servilletas y bolsas secas, limpios y sin restos","Restos de comida y cartón húmedo","Residuos de baño","Papel manteca sucio y servilletas usadas"], correcta:0 }
];

// Nivel 2 — Encargado: delivery, Data Live, caja, pedidos y seguridad.
const PREGUNTAS_ENCARGADO = [
  { id:101, texto:"¿Qué mide el Inaccuracy en Delivery?",
    opciones:["La cantidad de órdenes con errores generados desde la operación","El tiempo de espera del rider","La cantidad de órdenes del día","Los pedidos que cancela el cliente"], correcta:0 },
  { id:102, texto:"¿Cuál es el objetivo de Inaccuracy por local?",
    opciones:["Estar por debajo del 2,5%","Estar por debajo del 5%","Estar por debajo del 10%","Estar por encima del 2,5%"], correcta:0 },
  { id:103, texto:"¿Qué son los rechazos en delivery?",
    opciones:["Pedidos que el local cancela por falta de producto, fallas operativas o alta demanda","Pedidos que el cliente devuelve","Pedidos que el rider no retira","Pedidos con demora mayor a 10 minutos"], correcta:0 },
  { id:104, texto:"¿Qué mide el AWT (tiempo de espera evitable)?",
    opciones:["Órdenes donde el rider espera más de 10 minutos en el local hasta retirar el pedido","Órdenes entregadas fuera de horario","Órdenes con productos faltantes","El tiempo total de entrega al cliente"], correcta:0 },
  { id:105, texto:"Falta un producto de un pedido de delivery. ¿Qué hacemos?",
    opciones:["No enviamos productos sustitutos","Enviamos un producto parecido","Enviamos el pedido sin avisar","Agregamos una gaseosa de regalo"], correcta:0 },
  { id:106, texto:"Cuando llega el rider, ¿cómo confirmamos qué pedido entregarle?",
    opciones:["Con el nombre del cliente y los últimos 4 números de la orden, verificando el ticket antes de precintar","Con el nombre del rider","Por el color de la bolsa","Le damos el primero que esté listo"], correcta:0 },
  { id:107, texto:"¿Hasta qué hora se genera el pedido a fábrica en Data Live para recibirlo al día siguiente?",
    opciones:["Antes de las 15 hs (los sábados, el refuerzo antes de las 11 hs)","Antes de las 12 hs","Antes de las 18 hs","Antes de las 20 hs"], correcta:0 },
  { id:108, texto:"Las empanadas se piden a fábrica en múltiplos de:",
    opciones:["50 unidades","12 unidades","35 unidades","100 unidades"], correcta:0 },
  { id:109, texto:"¿Hasta cuándo se hace el pedido en Coca-Cola a un Click?",
    opciones:["Antes de las 12:00 hs del día anterior a la entrega","Antes de las 16:00 hs del día anterior","El mismo día de la entrega","Antes de las 15:00 hs del día anterior"], correcta:0 },
  { id:110, texto:"¿Cómo se hacen los egresos de caja?",
    opciones:["En fajos de $20.000 con el ticket de egreso, y se envían al cofre","En fajos de $10.000 sin comprobante","En un sobre al final del mes","Se entregan en mano al encargado siguiente"], correcta:0 },
  { id:111, texto:"¿Cuál es la función del Testigo en el manejo de dinero?",
    opciones:["Verificar que lo contado por el gerencial es correcto (doble control)","Contar el dinero solo","Firmar la planilla sin controlar","Llevar los bolsines al banco"], correcta:0 },
  { id:112, texto:"Sin generador, ¿cuándo se activa el protocolo de corte de luz?",
    opciones:["Cuando se confirma que el corte será mayor a 3 horas","Apenas se corta la luz","Cuando el corte supera 1 hora","Al día siguiente"], correcta:0 },
  { id:113, texto:"¿Dónde se enciende el grupo electrógeno?",
    opciones:["Siempre fuera del local","Dentro del local con la puerta abierta","En la cocina, cerca del tablero","Donde haya lugar"], correcta:0 },
  { id:114, texto:"Con el generador en marcha, ¿qué equipos son prioridad?",
    opciones:["Cámara frigorífica, DVR y horno a gas","La batea y los focos","Todas las térmicas, incluidas las tetrapolares","Las heladeras de bebidas"], correcta:0 },
  { id:115, texto:"Al recibir mercadería por traslado, ¿cómo controlamos la calidad de las empanadas?",
    opciones:["Cocinamos dos empanadas de cada bandeja (primera y última fila)","Probamos una empanada al azar","Solo revisamos el remito","No hace falta controlar"], correcta:0 },
  { id:116, texto:'¿Qué significa "PAS" ante un accidente?',
    opciones:["Proteger, Avisar, Socorrer","Prevenir, Actuar, Sanar","Parar, Analizar, Seguir","Pedir, Asistir, Salir"], correcta:0 },
  { id:117, texto:"Ocurre un accidente laboral a las 21 hs. ¿A quién se contacta para la denuncia?",
    opciones:["A la ART, con el Anexo 1 completo (SyH atiende de 9 a 18 hs)","Al equipo de Seguridad e Higiene al día siguiente","A nadie si no es grave","Solo a RR.HH."], correcta:0 },
  { id:118, texto:"Un cliente paga con un billete dudoso. ¿Qué hacemos?",
    opciones:["Pedimos asistencia al responsable de turno, doble verificación y solicitamos otro medio de pago","Lo aceptamos para no perder la venta","Lo retenemos y llamamos a la policía","Lo aceptamos y lo informamos al cierre"], correcta:0 },
  { id:119, texto:"Con la lapicera detectora, ¿qué indica una marca oscura o negra?",
    opciones:["Billete sospechoso","Billete auténtico","Billete de baja denominación","Que la lapicera está nueva"], correcta:0 },
  { id:120, texto:"¿Para qué tipo de fuego se usa el extintor K?",
    opciones:["Aceites vegetales y grasas de cocina","Tableros eléctricos","Papel y madera","Gasolina y solventes"], correcta:0 }
];

// Nivel 3 — Gerente: administración, inspecciones, RR.HH. y gestión.
const PREGUNTAS_GERENTE = [
  { id:201, texto:"¿Cuál es el orden del plan de carrera?",
    opciones:["Principiante → Entrenador → Encargado de turno → Gte. de Local → Supervisor → Asistente → Gte. de Operaciones",
      "Principiante → Encargado de turno → Entrenador → Gte. de Local → Asistente → Supervisor → Gte. de Operaciones",
      "Entrenador → Principiante → Encargado de turno → Supervisor → Gte. de Local → Asistente → Gte. de Operaciones",
      "Principiante → Entrenador → Gte. de Local → Encargado de turno → Supervisor → Gte. de Operaciones → Asistente"], correcta:0 },
  { id:202, texto:"¿Quiénes están autorizados a modificar el stock de cierre en Data Live?",
    opciones:["Solo los Gerentes de Operaciones","El Gerente de Local","Cualquier encargado de turno","Auditoría"], correcta:0 },
  { id:203, texto:'Al cargar el inventario de fin de mes, ¿qué pasa si se presiona "Volver"?',
    opciones:["El inventario queda en 0 y el mes siguiente no se podrá vender ningún producto","Se guarda automáticamente","Se envía a auditoría para revisión","No pasa nada"], correcta:0 },
  { id:204, texto:"¿Quiénes pueden visualizar las diferencias de stock?",
    opciones:["Gerentes Zonales, Gerentes de Operaciones, Asistentes y Auditoría","Todo el personal del local","Solo el Gerente de Local","Solo RR.HH."], correcta:0 },
  { id:205, texto:"¿Qué comprobante debe tener un gasto para ser válido?",
    opciones:["Factura A a nombre de la razón social del local","Ticket o Factura B","Factura C","Cualquier comprobante con foto"], correcta:0 },
  { id:206, texto:"Llega un inspector y labra un acta. ¿Qué corresponde?",
    opciones:["Avisar urgente al Gerente Zonal con foto del acta; el original se entrega dentro de las 48 hs","Guardar el acta hasta fin de mes","Avisar solo si hay multa","Entregar el original dentro de los 7 días"], correcta:0 },
  { id:207, texto:"¿Qué NO están autorizados a hacer los inspectores?",
    opciones:["Manipular la caja, hacer arqueos o tocar el punto de venta","Ingresar al local","Labrar un acta","Pedir documentación"], correcta:0 },
  { id:208, texto:"¿Cuál es la vigencia del REBA y con cuánta anticipación se avisa su renovación?",
    opciones:["1 año; avisar 60 días antes a Habilitaciones","2 años; avisar 30 días antes","1 año; avisar 7 días antes","6 meses; avisar 15 días antes"], correcta:0 },
  { id:209, texto:"Ante un daño en el inmueble (siniestro), ¿en qué plazo se envía la documentación?",
    opciones:["Dentro de las primeras 72 horas","Dentro de las 24 horas","Dentro de los 7 días","A fin de mes"], correcta:0 },
  { id:210, texto:"En iCheck, ¿qué dato se carga en el campo Legajo?",
    opciones:["El número de DNI, sin excepciones","El CUIL","Un número interno correlativo","El teléfono del empleado"], correcta:0 },
  { id:211, texto:"¿Quién carga las justificaciones en iCheck y cuándo?",
    opciones:["Exclusivamente el Gerente de Local, el mismo día a justificar","Cualquier empleado, a fin de mes","RR.HH., al liquidar","El encargado, una vez por semana"], correcta:0 },
  { id:212, texto:"¿Cuándo es el cierre de novedades para la liquidación?",
    opciones:["El día 20 (excepciones hasta el día 30)","El día 1","El día 15","El último día hábil del mes"], correcta:0 },
  { id:213, texto:"¿Desde cuándo son efectivos los ascensos?",
    opciones:["Desde el 1° de cada mes, comunicándolo el mes anterior","Desde el día que se comunica","Desde mitad de mes","A los 30 días de la evaluación"], correcta:0 },
  { id:214, texto:"En el tablero de asistencia de iCheck, ¿qué indica el color celeste?",
    opciones:["Fichada justificada","Ausencia de fichada","Fichada correcta","Fichada fuera de rango"], correcta:0 },
  { id:215, texto:"¿Quién está autorizado a enviar solicitudes de traslado de personal?",
    opciones:["Solo el Gerente Zonal (con la solicitud firmada por el Gerente Regional)","El Gerente de Local","El propio empleado","El encargado de turno"], correcta:0 },
  { id:216, texto:"¿Qué se requiere para cargar una licencia por enfermedad?",
    opciones:["Adjuntar el certificado médico; el reposo vale solo si está indicado en él","Solo el aviso por WhatsApp","Nada si es de un día","La firma del encargado"], correcta:0 },
  { id:217, texto:"Coca-Cola no entrega y hay quiebre de stock. ¿Cuál es el tope para comprar a un distribuidor externo?",
    opciones:["Hasta un 40% más caro que Coca-Cola, con autorización del Gte. Zonal y Regional","Sin tope, lo importante es tener stock","Hasta un 10% más caro","El encargado compra lo que haga falta"], correcta:0 },
  { id:218, texto:'¿Qué competencia se define como "identificar potenciales y gestionar los talentos del equipo"?',
    opciones:["Coaching","Liderazgo","Compromiso","Perfil comercial"], correcta:0 },
  { id:219, texto:"¿Cuál es la misión de Sabores Express?",
    opciones:["Satisfacer las necesidades del cliente con un vínculo comercial sustentable, la mejor calidad al menor precio posible","Ser la empresa líder en take away y delivery a nivel nacional","Honestidad, integridad y respeto","Abrir la mayor cantidad de locales posible"], correcta:0 },
  { id:220, texto:"¿Qué documento debe exhibirse en la pared del local, de fácil acceso para una inspección?",
    opciones:["REBA, fumigación, análisis de agua, habilitación y formulario 960 ARCA","Solo la habilitación","Ninguno, se muestran si los piden","El plan de carrera"], correcta:0 }
];

// Hamburguesas Extremas: mismos niveles y criterios que Sabores. Bancos pendientes de cargar desde su manual.
// Fuente: Manual de Operaciones Extremas (PDF "Manual Extremas 23.9").

// Nivel 1 — Entrenador: broiler, freidora, armado, vencimientos, higiene y atención.
const EXTREMAS_ENTRENADOR = [
  { id:301, texto:"¿A qué temperatura trabaja el broiler para la cocción de carnes?",
    opciones:["570 °F","400 °F","290 °F","185 °F"], correcta:0 },
  { id:302, texto:"¿Cuánto dura el recorrido de la cadena del broiler?",
    opciones:["2 minutos (120 segundos)","1 minuto (60 segundos)","4 minutos","30 segundos"], correcta:0 },
  { id:303, texto:"¿Cuántas carnes se colocan como máximo por fila en el broiler?",
    opciones:["4, en el centro de las bases y alejadas de los bordes","6, ocupando todo el ancho","2 por fila","8 por fila"], correcta:0 },
  { id:304, texto:"¿Qué temperatura interna debe tener la carne al salir del broiler?",
    opciones:["71 °C o más","Entre 40 °C y 50 °C","Entre 55 °C y 60 °C","30 °C"], correcta:0 },
  { id:305, texto:"¿Cómo debe estar la carne para ser apta para cocinar?",
    opciones:["Congelada, color rosa, sin hielo y que se separe fácilmente","Descongelada, blanda y rosa oscuro","Cristalizada, pálida y con exceso de hielo","A temperatura ambiente"], correcta:0 },
  { id:306, texto:"¿A qué temperatura debe estar el aceite de la freidora?",
    opciones:["Entre 170 °C y 185 °C","Entre 200 °C y 220 °C","Entre 150 °C y 160 °C","Entre 190 °C y 210 °C"], correcta:0 },
  { id:307, texto:"¿Cuáles son los enemigos del aceite?",
    opciones:["Agua, carbonilla, temperatura (más de 185 °C) y sal","Azúcar, luz y frío","Solo el agua","El uso de cestas limpias"], correcta:0 },
  { id:308, texto:"¿Cómo se activan las cestas de papas?",
    opciones:["Siempre de forma intercalada (1 - 3 - 2 - 4) para que el aceite no baje de temperatura","Todas juntas para ganar tiempo","De a una y esperando que termine la anterior","En el orden que se liberen"], correcta:0 },
  { id:309, tipo:"grilla", texto:"Completá con el color de envoltorio de cada hamburguesa.",
    filas:["Cuarto","Bacon","Clásica"],
    columnas:["Verde","Naranja","Bordó"], correcta:[1,2,0] },
  { id:310, texto:"¿Cuánto aderezo se aplica en la corona de las hamburguesas?",
    opciones:["1 vuelta y media","3 vueltas","Media vuelta","2 vueltas y media"], correcta:0 },
  { id:311, texto:"¿Cuánta cebolla lleva la hamburguesa Cuarto?",
    opciones:["15 gramos","10 gramos","35 gramos","25 gramos"], correcta:0 },
  { id:312, texto:"¿Qué temperatura interna debe tener la hamburguesa ya armada (medida en el transfer, entre el pan y la carne)?",
    opciones:["Entre 50 °C y 60 °C","71 °C o más","Entre 30 °C y 40 °C","Entre 80 °C y 90 °C"], correcta:0 },
  { id:313, texto:"Si la rodaja de tomate es mediana (ocupa el 50% de la corona), ¿cuántas se colocan?",
    opciones:["2 rodajas","1 rodaja","3 rodajas","4 rodajas"], correcta:0 },
  { id:314, texto:"Colocás bacon nuevo en la mesa de armado a las 10:00. ¿A qué hora marcás el reloj de vencimiento secundario?",
    opciones:["16:00 (6 horas)","14:00 (4 horas)","12:00 (2 horas)","22:00 (12 horas)"], correcta:0 },
  { id:315, texto:"¿A qué temperatura debe estar el freezer (carnes, papas y bacon)?",
    opciones:["Entre -15 °C y -23 °C","Entre 0 °C y 5 °C","Entre -5 °C y 0 °C","Entre -30 °C y -40 °C"], correcta:0 },
  { id:316, texto:"¿Cuál es el tiempo de cocción de los nuggets?",
    opciones:["3:45 minutos","2 minutos","5 minutos","7 minutos"], correcta:0 },
  { id:317, texto:"¿Qué pinza se usa para los nuggets y el medallón de pollo?",
    opciones:["La pinza naranja, nunca la de carnes, para evitar contaminación cruzada","La misma pinza de las carnes","Cualquier pinza limpia","Se manipulan con la mano con guantes"], correcta:0 },
  { id:318, texto:"Una vez armada la hamburguesa de pollo, ¿qué vencimiento se marca con el lápiz de cera?",
    opciones:["15 minutos","30 minutos","1 hora","5 minutos"], correcta:0 },
  { id:319, texto:"¿Cuántas vueltas de helado lleva el sundae?",
    opciones:["3 ½ vueltas","2 ½ vueltas","4 ½ vueltas","5 vueltas"], correcta:0 },
  { id:320, texto:"Además de al ingresar, al cambiar de tarea o tocar dinero, ¿cada cuánto nos lavamos las manos?",
    opciones:["Cada 60 minutos","Cada 4 horas","Solo al terminar el turno","Una vez por turno"], correcta:0 }
];

// Nivel 2 — Encargado: limpieza y control de equipos, retención, delivery, caja y seguridad.
const EXTREMAS_ENCARGADO = [
  { id:401, texto:"Antes de apagar el broiler para la limpieza, ¿qué se hace?",
    opciones:["Se deja encendido y sin productos 15 minutos para quemar los residuos de las cadenas","Se apaga de inmediato y se desarma","Se moja con agua para enfriarlo","Se deja encendido 1 hora con productos"], correcta:0 },
  { id:402, texto:"Durante el enfriamiento del broiler, ¿qué pasa con la campana de ventilación?",
    opciones:["Se mantiene encendida: apagarla puede provocar un incendio","Se apaga para ahorrar energía","Se apaga y se abre la puerta","Da igual"], correcta:0 },
  { id:403, texto:"¿Cómo se limpia el catalizador del broiler?",
    opciones:["Cepillado suave, 1 hora solo en agua caliente y secado al aire toda la noche; sin desengrasante, detergente ni esponja 3M","Con desengrasante y esponja 3M","En el lavavajillas","Con detergente y agua fría"], correcta:0 },
  { id:404, texto:"¿Por qué no se usa desengrasante sobre el teflón del rodadero?",
    opciones:["Porque entra en contacto directo con la carne y el químico podría contaminarla","Porque lo decolora","Porque no limpia bien","Sí se usa desengrasante"], correcta:0 },
  { id:405, texto:"¿Cada cuánto se limpian los cambros del broiler?",
    opciones:["Cada 4 horas","Una vez por semana","Solo al cierre","Cada 30 minutos"], correcta:0 },
  { id:406, texto:"¿Cuándo se realiza el Boil Out de la freidora?",
    opciones:["El último día de cada mes","Todos los días","Lunes y jueves","Una vez al año"], correcta:0 },
  { id:407, texto:"En el control de vatiaje del microondas (inicio de cada mes), ¿qué resultado debe dar?",
    opciones:["Superior a 1250 W","Superior a 800 W","Exactamente 1000 W","Inferior a 1250 W"], correcta:0 },
  { id:408, texto:"Al calibrar el pirómetro en un vaso con hielo y agua fría, ¿qué debe indicar?",
    opciones:["Entre 0 °C y 4 °C","Entre 10 °C y 15 °C","Exactamente 20 °C","Entre -10 °C y -5 °C"], correcta:0 },
  { id:409, texto:"¿Cuál es la retención máxima de las carnes en el PHU?",
    opciones:["30 minutos","2 horas","10 minutos","Hasta el cierre"], correcta:0 },
  { id:410, texto:"Si detectás una carne cruda al salir del broiler, ¿qué corresponde?",
    opciones:["Realizar obligatoriamente el corte de seguridad en la siguiente unidad","Servirla igual si está caliente","Pasarla por el microondas","No hace falta ningún control"], correcta:0 },
  { id:411, texto:"Nuggets en el PHU (rush): ¿cuál es la retención y cómo se guardan?",
    opciones:["30 minutos, sin tapa y hasta 50 nuggets por cambro","2 horas con tapa","10 minutos en el BIN de hamburguesas","60 minutos con tapa cerrada"], correcta:0 },
  { id:412, texto:"En la pantalla de cocina (Datalive Kitchen), ¿desde qué tiempo un pedido es crítico?",
    opciones:["Desde 4 minutos","Desde 2 minutos","Desde 6 minutos","Desde 10 minutos"], correcta:0 },
  { id:413, texto:"¿Cuál es el objetivo de Inaccuracy por local en Extremas?",
    opciones:["Estar por debajo del 2%","Estar por debajo del 5%","Estar por debajo del 10%","Estar por encima del 2%"], correcta:0 },
  { id:414, texto:"¿Qué calificación debemos garantizar en PedidosYa?",
    opciones:["Mayor a 4.2","Mayor a 3","Mayor a 2.5","No importa la calificación"], correcta:0 },
  { id:415, texto:"Al cierre del día, ¿cuánto puede tener como máximo la caja chica?",
    opciones:["200.000 ARS","100.000 ARS","500.000 ARS","No tiene límite"], correcta:0 },
  { id:416, texto:"¿Cuándo se completa la planilla de retiro de disponibles?",
    opciones:["Cada vez que depositamos, no cuando llega el recaudador","Cuando llega el recaudador","Una vez por semana","A fin de mes"], correcta:0 },
  { id:417, texto:"Coca-Cola no entregó y hay que comprar a un distribuidor externo. ¿Qué tenemos en cuenta?",
    opciones:["Comprar solo lo mínimo: el distribuidor externo es un 40% más caro","Comprar todo el pedido original","Comprar el doble para no quedarnos sin stock","No avisar a nadie"], correcta:0 },
  { id:418, texto:"Al recibir la mercadería de Coca-Cola, ¿qué se hace en Datalive?",
    opciones:["Ingresarla el mismo día seleccionando el proveedor y subir la foto de la factura","Ingresarla a fin de semana","Solo guardar la factura en el cajón","Ingresarla cuando se termine el stock"], correcta:0 },
  { id:419, texto:"Ocurre un accidente laboral a las 22 hs. ¿Qué corresponde?",
    opciones:["Aplicar PAS, avisar al Gerente Zonal/Regional y llamar a la ART con el Anexo 1 completo","Esperar al día siguiente para avisar a Seguridad e Higiene","Llamar a la ART sin tomar datos","No hacer nada si no fue grave"], correcta:0 },
  { id:420, texto:"Un cliente paga con un billete dudoso. ¿Qué hacemos?",
    opciones:["Pedimos asistencia al responsable de turno, doble verificación y solicitamos otro medio de pago","Lo aceptamos para no perder la venta","Lo retenemos y llamamos a la policía","Lo aceptamos y lo informamos al cierre"], correcta:0 }
];

// Nivel 3 — Gerente: inspecciones, documentación, siniestros, iCheck y gestión.
const EXTREMAS_GERENTE = [
  { id:501, texto:"Un inspector labra un acta en el local. ¿Qué corresponde?",
    opciones:["Avisar de inmediato al Gerente Zonal con foto del acta; el original se entrega dentro de las 48 hs","Guardar el acta hasta fin de mes","Avisar solo si hay multa","Entregar el original dentro de los 7 días"], correcta:0 },
  { id:502, texto:"¿Qué NO están autorizados a hacer los inspectores?",
    opciones:["Manipular la caja de dinero, hacer arqueos o tocar el punto de venta","Ingresar al local si lo requieren","Labrar un acta","Pedir la credencial y documentación"], correcta:0 },
  { id:503, texto:"¿Cuál es la vigencia del REBA y con cuánta anticipación se avisa su renovación?",
    opciones:["1 año; avisar 60 días antes a Habilitaciones","2 años; avisar 30 días antes","1 año; avisar 7 días antes","6 meses; avisar 15 días antes"], correcta:0 },
  { id:504, texto:"Cuando el proveedor se lleva los matafuegos para recargarlos, ¿qué debe dejar?",
    opciones:["Un matafuego provisorio con su oblea correspondiente","Nada, se devuelven en el día","Solo el remito","Un cartel de aviso"], correcta:0 },
  { id:505, texto:"Ante un daño en el inmueble, ¿en qué plazo se envía la documentación al seguro?",
    opciones:["Dentro de las primeras 72 horas; pasado el plazo el seguro no cubre","Dentro de los 15 días","A fin de mes","No hay plazo"], correcta:0 },
  { id:506, texto:"Un cliente se cae en la rampa de acceso (accidente de tercero). ¿Qué hace el Gerente Regional?",
    opciones:["Envía el mismo día un email a RRHH y Legales con la planilla de denuncia de siniestro","Espera a que el cliente reclame","Lo informa en la reunión mensual","Nada, lo resuelve el local"], correcta:0 },
  { id:507, texto:"En iCheck, ¿qué día de la semana se cargan los horarios del equipo?",
    opciones:["Los jueves","Los lunes","Los viernes","El último día del mes"], correcta:0 },
  { id:508, texto:"¿Cómo se carga en iCheck un horario nocturno (00:00 a 05:00)?",
    opciones:["Activando el ícono de la luna","Como un horario normal","Se carga al día siguiente","No se carga"], correcta:0 },
  { id:509, texto:"¿Cómo se carga un día de franco en la carga de horarios?",
    opciones:["No se carga horario: los campos quedan vacíos","Con horario 00:00 a 00:00","Con la palabra FRANCO","Con el horario habitual"], correcta:0 },
  { id:510, texto:"En una jornada itinerante (varios locales), ¿cuánto pueden sumar como máximo los trayectos?",
    opciones:["1 hora","2 horas","30 minutos","No hay límite"], correcta:0 },
  { id:511, texto:"En iCheck, ¿qué dato se carga en el campo Legajo?",
    opciones:["El número de DNI, sin excepciones","El CUIL","Un número interno correlativo","El teléfono"], correcta:0 },
  { id:512, texto:"¿Desde cuándo son efectivos los ascensos?",
    opciones:["Desde el 1° de cada mes, comunicándolo el mes anterior","Desde el día que se comunica","Desde mitad de mes","A los 30 días de la evaluación"], correcta:0 },
  { id:513, texto:"¿Cuándo se carga la baja de un empleado en iCheck?",
    opciones:["El mismo día en que el colaborador notifica su desvinculación","A fin de mes","Cuando llega el telegrama","Al liquidar el sueldo"], correcta:0 },
  { id:514, texto:"Traslados de personal: ¿qué es correcto?",
    opciones:["Solo el Gerente Zonal envía la solicitud, firmada por el Gerente Regional; no se puede volver a una unidad anterior con la misma razón social","Lo pide el empleado directamente a RRHH","Lo decide el encargado de turno","Se puede volver a cualquier local sin solicitud"], correcta:0 },
  { id:515, texto:"¿Qué se requiere para cargar una licencia por enfermedad?",
    opciones:["Adjuntar el certificado médico; el reposo vale solo si está indicado en él","Solo el aviso por WhatsApp","Nada si es de un día","La firma del encargado"], correcta:0 },
  { id:516, texto:"¿Por qué se lanzó la Clásica Deluxe exclusiva de PedidosYa?",
    opciones:["Para traccionar ventas en locales que no alcanzan el promedio de combos mensuales o están por debajo de las ventas comp 2025","Para reemplazar a la Clásica en todos los locales","Para usar sobrante de bacon","Para vender solo en mostrador"], correcta:0 },
  { id:517, texto:"¿Por qué la hamburguesa de pollo pasó del pan grande al pan Junior?",
    opciones:["Para unificar el estándar de armado en todos los locales y la rentabilidad del combo","Porque el pan grande se discontinuó","Por pedido de los clientes","Para bajar el tiempo de tostado"], correcta:0 },
  { id:518, texto:"¿Qué documentación debe estar exhibida en la pared del local, de fácil acceso para una inspección?",
    opciones:["REBA, fumigación, análisis de agua, habilitación comercial y formulario 960 ARCA","Solo la habilitación","Ninguna, se muestra si la piden","El organigrama del local"], correcta:0 },
  { id:519, texto:"Si no cumplimos el procedimiento de pedido a Coca-Cola (en tiempo y forma) y compramos afuera, ¿qué pasa?",
    opciones:["Compras no puede gestionar el reintegro y el sobreprecio queda a cargo del local","Coca-Cola reintegra igual","El distribuidor devuelve la diferencia","No pasa nada"], correcta:0 },
  { id:520, texto:"¿Cuál es la misión de la compañía?",
    opciones:["Satisfacer las necesidades del cliente con un vínculo comercial sustentable, la mejor calidad al menor precio posible","Ser la empresa líder en take away y delivery a nivel nacional","Honestidad, integridad y respeto","Abrir la mayor cantidad de locales posible"], correcta:0 }
];

// Acceso único para quien lo cargue desde afuera: BANCOS[marca][nivel].
window.BANCOS = {
  sabores: { entrenador: PREGUNTAS_ENTRENADOR, encargado: PREGUNTAS_ENCARGADO, gerente: PREGUNTAS_GERENTE },
  hex:     { entrenador: EXTREMAS_ENTRENADOR, encargado: EXTREMAS_ENCARGADO, gerente: EXTREMAS_GERENTE }
};
